insert into Branch (id, location, yearStart) values (1, 'Kura', 2001);
insert into Branch (id, location, yearStart) values (2, 'Gainesville', 2012);
insert into Branch (id, location, yearStart) values (3, 'Putang', 1990);
insert into Branch (id, location, yearStart) values (4, 'Santa Rosa de Cabal', 2004);
insert into Branch (id, location, yearStart) values (5, 'Vitry-sur-Seine', 1997);
insert into Branch (id, location, yearStart) values (6, 'Casal', 2005);
insert into Branch (id, location, yearStart) values (7, 'Batutulis', 1996);
insert into Branch (id, location, yearStart) values (8, 'Hongmiao', 2002);
insert into Branch (id, location, yearStart) values (9, 'Chiguang', 1983);
insert into Branch (id, location, yearStart) values (10, 'Tortosendo', 1987);
insert into Branch (id, location, yearStart) values (11, 'Delicias', 2011);
insert into Branch (id, location, yearStart) values (12, 'Concepción', 2004);
insert into Branch (id, location, yearStart) values (13, 'Sabóia', 1990);
insert into Branch (id, location, yearStart) values (14, 'Fernández', 2012);
insert into Branch (id, location, yearStart) values (15, 'Shadui', 1999);
insert into Branch (id, location, yearStart) values (16, 'Zhendu', 2012);
insert into Branch (id, location, yearStart) values (17, 'Shuangqiao', 1999);
insert into Branch (id, location, yearStart) values (18, 'Matsubase', 2007);
insert into Branch (id, location, yearStart) values (19, 'Xinshi', 1997);
insert into Branch (id, location, yearStart) values (20, 'Dongfeng', 2009);
insert into Branch (id, location, yearStart) values (21, 'Dulangan', 2003);
insert into Branch (id, location, yearStart) values (22, 'Eqbālīyeh', 2009);
insert into Branch (id, location, yearStart) values (23, 'Pura', 2008);
insert into Branch (id, location, yearStart) values (24, 'Subaykhān', 2000);
insert into Branch (id, location, yearStart) values (25, 'Chiguirip', 2007);
insert into Branch (id, location, yearStart) values (26, 'Älvdalen', 2000);
insert into Branch (id, location, yearStart) values (27, 'Tucano', 1994);
insert into Branch (id, location, yearStart) values (28, 'København', 2000);
insert into Branch (id, location, yearStart) values (29, 'Itoigawa', 1995);
insert into Branch (id, location, yearStart) values (30, 'Batan', 1994);
insert into Branch (id, location, yearStart) values (31, 'Fenglin', 2006);
insert into Branch (id, location, yearStart) values (32, 'Anjirmuara', 2007);
insert into Branch (id, location, yearStart) values (33, 'Alannay', 2001);
insert into Branch (id, location, yearStart) values (34, 'Galán', 1998);
insert into Branch (id, location, yearStart) values (35, 'Port Erin', 1985);
insert into Branch (id, location, yearStart) values (36, 'San Miguel Dueñas', 1993);
insert into Branch (id, location, yearStart) values (37, 'Habana del Este', 2009);
insert into Branch (id, location, yearStart) values (38, 'Unquillo', 1993);
insert into Branch (id, location, yearStart) values (39, 'Hakha', 1968);
insert into Branch (id, location, yearStart) values (40, 'Xiongji', 1999);
insert into Branch (id, location, yearStart) values (41, 'Mucifal', 1993);
insert into Branch (id, location, yearStart) values (42, 'Ozalj', 2012);
insert into Branch (id, location, yearStart) values (43, 'Oslo', 1990);
insert into Branch (id, location, yearStart) values (44, 'Paços de Ferreira', 1996);
insert into Branch (id, location, yearStart) values (45, 'Aíyira', 2010);
insert into Branch (id, location, yearStart) values (46, 'Ożarowice', 2005);
insert into Branch (id, location, yearStart) values (47, 'Xinfeng', 1994);
insert into Branch (id, location, yearStart) values (48, 'Panjgūr', 2008);
insert into Branch (id, location, yearStart) values (49, 'Aughrim', 2006);
insert into Branch (id, location, yearStart) values (50, 'Kuvshinovo', 2003);
insert into Branch (id, location, yearStart) values (51, 'Baykonyr', 2007);
insert into Branch (id, location, yearStart) values (52, 'Clamart', 2001);
insert into Branch (id, location, yearStart) values (53, 'Bambous Virieux', 1993);
insert into Branch (id, location, yearStart) values (54, 'Haolaishan', 1997);
insert into Branch (id, location, yearStart) values (55, 'Nangalisan', 1987);
insert into Branch (id, location, yearStart) values (56, 'Erandique', 2008);
insert into Branch (id, location, yearStart) values (57, 'Gresik', 2002);
insert into Branch (id, location, yearStart) values (58, 'Itupiranga', 2011);
insert into Branch (id, location, yearStart) values (59, 'Dosso', 2007);
insert into Branch (id, location, yearStart) values (60, 'Kholm', 2001);
insert into Branch (id, location, yearStart) values (61, 'Ādilpur', 2000);
insert into Branch (id, location, yearStart) values (62, 'Borås', 2012);
insert into Branch (id, location, yearStart) values (63, 'Kinloch', 2000);
insert into Branch (id, location, yearStart) values (64, 'Pananaw', 1999);
insert into Branch (id, location, yearStart) values (65, 'Ardino', 2008);
insert into Branch (id, location, yearStart) values (66, 'Cunliji', 1994);
insert into Branch (id, location, yearStart) values (67, 'Kitahiroshima', 2007);
insert into Branch (id, location, yearStart) values (68, 'Tetaf', 2010);
insert into Branch (id, location, yearStart) values (69, 'Qitan', 2009);
insert into Branch (id, location, yearStart) values (70, 'Luhe', 1999);
insert into Branch (id, location, yearStart) values (71, 'Taibai', 2012);
insert into Branch (id, location, yearStart) values (72, 'Banjar Penyalin', 2000);
insert into Branch (id, location, yearStart) values (73, 'Magsaysay', 2002);
insert into Branch (id, location, yearStart) values (74, 'San Lorenzo de Esmeraldas', 2006);
insert into Branch (id, location, yearStart) values (75, 'Goúvai', 1998);
insert into Branch (id, location, yearStart) values (76, 'Redcliff', 1997);
insert into Branch (id, location, yearStart) values (77, 'Zelenodolsk', 1990);
insert into Branch (id, location, yearStart) values (78, 'Brive-la-Gaillarde', 1989);
insert into Branch (id, location, yearStart) values (79, 'Krajan Langenharjo', 1994);
insert into Branch (id, location, yearStart) values (80, 'Nardaran', 1988);
insert into Branch (id, location, yearStart) values (81, 'Huangyang', 1993);
insert into Branch (id, location, yearStart) values (82, 'Yuracyacu', 2001);
insert into Branch (id, location, yearStart) values (83, 'Brongkah', 2007);
insert into Branch (id, location, yearStart) values (84, 'Río Segundo', 2007);
insert into Branch (id, location, yearStart) values (85, 'Fresno', 1990);
insert into Branch (id, location, yearStart) values (86, 'Bhola', 1992);
insert into Branch (id, location, yearStart) values (87, 'Oyabe', 1987);
insert into Branch (id, location, yearStart) values (88, 'Morro Agudo', 2012);
insert into Branch (id, location, yearStart) values (89, 'Saihan Tal', 2005);
insert into Branch (id, location, yearStart) values (90, 'Kafr ad Dawwār', 1989);
insert into Branch (id, location, yearStart) values (91, 'Saguenay', 1997);
insert into Branch (id, location, yearStart) values (92, 'Al Qanāţir al Khayrīyah', 1999);
insert into Branch (id, location, yearStart) values (93, 'Muarabuliti', 2005);
insert into Branch (id, location, yearStart) values (94, 'Xingtai', 2012);
insert into Branch (id, location, yearStart) values (95, 'Dassa-Zoumé', 1999);
insert into Branch (id, location, yearStart) values (96, 'Lučina', 2006);
insert into Branch (id, location, yearStart) values (97, 'Agía Triáda', 2006);
insert into Branch (id, location, yearStart) values (98, 'Ferrol', 1996);
insert into Branch (id, location, yearStart) values (99, 'Tanahedang', 1986);
insert into Branch (id, location, yearStart) values (100, 'Hinapalanan', 2003);
insert into Branch (id, location, yearStart) values (101, 'Banjar Kajanan', 1988);
insert into Branch (id, location, yearStart) values (102, 'Irákleion', 2010);
insert into Branch (id, location, yearStart) values (103, 'Bettendorf', 1996);
insert into Branch (id, location, yearStart) values (104, 'Fengtang', 2001);
insert into Branch (id, location, yearStart) values (105, 'Koh Kong', 1995);
insert into Branch (id, location, yearStart) values (106, 'Kista', 1993);
insert into Branch (id, location, yearStart) values (107, 'Sukakerta', 2012);
insert into Branch (id, location, yearStart) values (108, 'Zhdanov', 1994);
insert into Branch (id, location, yearStart) values (109, 'Lalukoen Dua', 2009);
insert into Branch (id, location, yearStart) values (110, 'El Triunfo', 2002);
insert into Branch (id, location, yearStart) values (111, 'Gävle', 1998);
insert into Branch (id, location, yearStart) values (112, 'Acton Vale', 2005);
insert into Branch (id, location, yearStart) values (113, 'Sydney', 2004);
insert into Branch (id, location, yearStart) values (114, 'Osorno', 1999);
insert into Branch (id, location, yearStart) values (115, 'Chillia', 2003);
insert into Branch (id, location, yearStart) values (116, 'Beisijia', 1996);
insert into Branch (id, location, yearStart) values (117, 'Pamatang', 1993);
insert into Branch (id, location, yearStart) values (118, 'Baiyang', 2000);
insert into Branch (id, location, yearStart) values (119, 'Gorna Oryakhovitsa', 2013);
insert into Branch (id, location, yearStart) values (120, 'Huayuan', 2009);
insert into Branch (id, location, yearStart) values (121, 'Haimen', 1992);
insert into Branch (id, location, yearStart) values (122, 'Syców', 2005);
insert into Branch (id, location, yearStart) values (123, 'Isheyevka', 1996);
insert into Branch (id, location, yearStart) values (124, 'Lampitak', 2001);
insert into Branch (id, location, yearStart) values (125, 'Zhongxing', 2000);
insert into Branch (id, location, yearStart) values (126, 'Montpellier', 2009);
insert into Branch (id, location, yearStart) values (127, 'Billdal', 2005);
insert into Branch (id, location, yearStart) values (128, 'Taoyuan', 2004);
insert into Branch (id, location, yearStart) values (129, 'Hengpi', 1992);
insert into Branch (id, location, yearStart) values (130, 'La Cruz de Taratara', 1997);
insert into Branch (id, location, yearStart) values (131, 'Górki Wielkie', 2000);
insert into Branch (id, location, yearStart) values (132, 'Safakulevo', 1991);
insert into Branch (id, location, yearStart) values (133, 'Kochani', 2004);
insert into Branch (id, location, yearStart) values (134, 'Kugri', 1993);
insert into Branch (id, location, yearStart) values (135, 'Belene', 2003);
insert into Branch (id, location, yearStart) values (136, 'Jan Kempdorp', 2012);
insert into Branch (id, location, yearStart) values (137, 'Shicheng', 2004);
insert into Branch (id, location, yearStart) values (138, 'Cajamarca', 2003);
insert into Branch (id, location, yearStart) values (139, 'Baiyin', 1991);
insert into Branch (id, location, yearStart) values (140, 'Bronx', 1985);
insert into Branch (id, location, yearStart) values (141, 'Dongzhang', 1956);
insert into Branch (id, location, yearStart) values (142, 'Naze', 2005);
insert into Branch (id, location, yearStart) values (143, 'Severnyy', 1994);
insert into Branch (id, location, yearStart) values (144, 'Santiago Puringla', 1999);
insert into Branch (id, location, yearStart) values (145, 'Göteborg', 2005);
insert into Branch (id, location, yearStart) values (146, 'No Kunda', 2002);
insert into Branch (id, location, yearStart) values (147, 'Oviedo', 2002);
insert into Branch (id, location, yearStart) values (148, 'Rovira', 2005);
insert into Branch (id, location, yearStart) values (149, 'Ribeiro', 2008);
insert into Branch (id, location, yearStart) values (150, 'Parakanhonje Wetan', 1973);
insert into Branch (id, location, yearStart) values (151, 'Penhascoso', 2003);
insert into Branch (id, location, yearStart) values (152, 'Ayorou', 2000);
insert into Branch (id, location, yearStart) values (153, 'Greenhills', 2012);
insert into Branch (id, location, yearStart) values (154, 'Châu Thành', 2004);
insert into Branch (id, location, yearStart) values (155, 'Vinica', 1988);
insert into Branch (id, location, yearStart) values (156, 'Maicao', 1995);
insert into Branch (id, location, yearStart) values (157, 'Hekou', 2009);
insert into Branch (id, location, yearStart) values (158, 'Yiqi', 2005);
insert into Branch (id, location, yearStart) values (159, 'Rusnė', 1992);
insert into Branch (id, location, yearStart) values (160, 'Bačka Topola', 1993);
insert into Branch (id, location, yearStart) values (161, 'Marne-la-Vallée', 1999);
insert into Branch (id, location, yearStart) values (162, 'Muromtsevo', 1995);
insert into Branch (id, location, yearStart) values (163, 'Hässelby', 2000);
insert into Branch (id, location, yearStart) values (164, 'Changning', 2009);
insert into Branch (id, location, yearStart) values (165, 'Satte', 2012);
insert into Branch (id, location, yearStart) values (166, 'Glafirovka', 1994);
insert into Branch (id, location, yearStart) values (167, 'Yafran', 1992);
insert into Branch (id, location, yearStart) values (168, 'Pamplona/Iruña', 2006);
insert into Branch (id, location, yearStart) values (169, 'Andrushivka', 1989);
insert into Branch (id, location, yearStart) values (170, 'Johogunung', 1968);
insert into Branch (id, location, yearStart) values (171, 'Linköping', 1992);
insert into Branch (id, location, yearStart) values (172, 'Jurh', 1993);
insert into Branch (id, location, yearStart) values (173, 'Jianli', 2006);
insert into Branch (id, location, yearStart) values (174, 'Grugul', 1998);
insert into Branch (id, location, yearStart) values (175, 'Wuning', 2008);
insert into Branch (id, location, yearStart) values (176, 'Xambabazar', 2011);
insert into Branch (id, location, yearStart) values (177, 'Sampao', 2011);
insert into Branch (id, location, yearStart) values (178, 'Mojorembun', 2004);
insert into Branch (id, location, yearStart) values (179, 'Rouen', 1989);
insert into Branch (id, location, yearStart) values (180, 'Kecskemét', 1994);
insert into Branch (id, location, yearStart) values (181, 'Donja Brela', 2003);
insert into Branch (id, location, yearStart) values (182, 'Strasbourg', 2001);
insert into Branch (id, location, yearStart) values (183, 'Wang Thonglang', 1993);
insert into Branch (id, location, yearStart) values (184, 'Ullubiyaul', 1999);
insert into Branch (id, location, yearStart) values (185, 'Calibishie', 1998);
insert into Branch (id, location, yearStart) values (186, 'Bangad', 2003);
insert into Branch (id, location, yearStart) values (187, 'Venda Nova', 2005);
insert into Branch (id, location, yearStart) values (188, 'Chirilagua', 2003);
insert into Branch (id, location, yearStart) values (189, 'Tomilino', 2011);
insert into Branch (id, location, yearStart) values (190, 'Cimanglid', 1987);
insert into Branch (id, location, yearStart) values (191, 'Shenkou', 1985);
insert into Branch (id, location, yearStart) values (192, 'Åby', 1995);
insert into Branch (id, location, yearStart) values (193, 'Myrnyy', 2003);
insert into Branch (id, location, yearStart) values (194, 'Skellefteå', 2010);
insert into Branch (id, location, yearStart) values (195, 'Asnières-sur-Seine', 1996);
insert into Branch (id, location, yearStart) values (196, 'Springfield', 2005);
insert into Branch (id, location, yearStart) values (197, 'Angoulême', 1994);
insert into Branch (id, location, yearStart) values (198, 'Boticas', 1999);
insert into Branch (id, location, yearStart) values (199, 'Fenglu', 2011);
insert into Branch (id, location, yearStart) values (200, 'Huambalpa', 2009);
insert into Branch (id, location, yearStart) values (201, 'Zhaxirabdain', 2009);
insert into Branch (id, location, yearStart) values (202, 'Castleblayney', 2011);
insert into Branch (id, location, yearStart) values (203, 'Wąwolnica', 2011);
insert into Branch (id, location, yearStart) values (204, 'Mingjiu', 1969);
insert into Branch (id, location, yearStart) values (205, 'Pedroso', 2010);
insert into Branch (id, location, yearStart) values (206, 'Zeleneč', 2001);
insert into Branch (id, location, yearStart) values (207, 'Alfta', 1997);
insert into Branch (id, location, yearStart) values (208, 'Guiuan', 1988);
insert into Branch (id, location, yearStart) values (209, 'Souto', 2008);
insert into Branch (id, location, yearStart) values (210, 'Aktsyabrski', 2010);
insert into Branch (id, location, yearStart) values (211, 'Kabīrwāla', 2004);
insert into Branch (id, location, yearStart) values (212, 'Wentugaole', 2004);
insert into Branch (id, location, yearStart) values (213, 'Gazimurskiy Zavod', 1997);
insert into Branch (id, location, yearStart) values (214, 'Ghanzi', 1984);
insert into Branch (id, location, yearStart) values (215, 'Nicasio', 1995);
insert into Branch (id, location, yearStart) values (216, 'Xidajie', 2012);
insert into Branch (id, location, yearStart) values (217, 'Heqiao', 2001);
insert into Branch (id, location, yearStart) values (218, 'Corinto', 1987);
insert into Branch (id, location, yearStart) values (219, 'Songqiao', 2007);
insert into Branch (id, location, yearStart) values (220, 'Guling', 2001);
insert into Branch (id, location, yearStart) values (221, 'San Cristobal', 1968);
insert into Branch (id, location, yearStart) values (222, 'Bella Vista', 2002);
insert into Branch (id, location, yearStart) values (223, 'Toutai', 1998);
insert into Branch (id, location, yearStart) values (224, 'Sam Ngam', 1993);
insert into Branch (id, location, yearStart) values (225, 'Xiaoguai', 2011);
insert into Branch (id, location, yearStart) values (226, 'Dióni', 1990);
insert into Branch (id, location, yearStart) values (227, 'Niquinohomo', 2001);
insert into Branch (id, location, yearStart) values (228, 'Planovskoye', 2006);
insert into Branch (id, location, yearStart) values (229, 'Taixi', 1992);
insert into Branch (id, location, yearStart) values (230, 'Shupenzë', 2002);
insert into Branch (id, location, yearStart) values (231, 'Clonskeagh', 2003);
insert into Branch (id, location, yearStart) values (232, 'Kimanuit', 2003);
insert into Branch (id, location, yearStart) values (233, 'Rivière-du-Loup', 1996);
insert into Branch (id, location, yearStart) values (234, 'Krajan', 1988);
insert into Branch (id, location, yearStart) values (235, 'Dongqinggou', 1996);
insert into Branch (id, location, yearStart) values (236, 'Itajuípe', 2004);
insert into Branch (id, location, yearStart) values (237, 'Velyki Sorochyntsi', 2010);
insert into Branch (id, location, yearStart) values (238, 'Oguta', 1998);
insert into Branch (id, location, yearStart) values (239, 'Komga', 1995);
insert into Branch (id, location, yearStart) values (240, 'Dolinsk', 2012);
insert into Branch (id, location, yearStart) values (241, 'Garnich', 1995);
insert into Branch (id, location, yearStart) values (242, 'Chamical', 1995);
insert into Branch (id, location, yearStart) values (243, 'Situsari', 2005);
insert into Branch (id, location, yearStart) values (244, 'Porto Velho', 1989);
insert into Branch (id, location, yearStart) values (245, 'Panggulan', 1999);
insert into Branch (id, location, yearStart) values (246, 'Soras', 2004);
insert into Branch (id, location, yearStart) values (247, 'Pag', 1989);
insert into Branch (id, location, yearStart) values (248, 'Agnibilékrou', 2001);
insert into Branch (id, location, yearStart) values (249, 'Dầu Tiếng', 1993);
insert into Branch (id, location, yearStart) values (250, 'Boussé', 2011);
insert into Branch (id, location, yearStart) values (251, 'Santo Aleixo', 1986);
insert into Branch (id, location, yearStart) values (252, 'Żabno', 1997);
insert into Branch (id, location, yearStart) values (253, 'Nymburk', 2004);
insert into Branch (id, location, yearStart) values (254, 'Leme', 2005);
insert into Branch (id, location, yearStart) values (255, 'Érd', 2011);
insert into Branch (id, location, yearStart) values (256, 'Muldersdriseloop', 2012);
insert into Branch (id, location, yearStart) values (257, 'Pitanga', 1993);
insert into Branch (id, location, yearStart) values (258, 'Wawa', 1992);
insert into Branch (id, location, yearStart) values (259, 'Dallas', 2008);
insert into Branch (id, location, yearStart) values (260, 'Épinal', 1926);
insert into Branch (id, location, yearStart) values (261, 'Milano', 2008);
insert into Branch (id, location, yearStart) values (262, 'Erbil', 1987);
insert into Branch (id, location, yearStart) values (263, 'Fushë-Muhurr', 2009);
insert into Branch (id, location, yearStart) values (264, 'Yangmadao', 2012);
insert into Branch (id, location, yearStart) values (265, 'Satipo', 1997);
insert into Branch (id, location, yearStart) values (266, 'Kambing', 2009);
insert into Branch (id, location, yearStart) values (267, 'Lupo', 2010);
insert into Branch (id, location, yearStart) values (268, 'Hobart', 1993);
insert into Branch (id, location, yearStart) values (269, 'Rybache', 2010);
insert into Branch (id, location, yearStart) values (270, 'Lajeado', 2008);
insert into Branch (id, location, yearStart) values (271, 'Heting', 1994);
insert into Branch (id, location, yearStart) values (272, 'Biao', 2000);
insert into Branch (id, location, yearStart) values (273, 'Oebaki', 1993);
insert into Branch (id, location, yearStart) values (274, 'Montpellier', 2004);
insert into Branch (id, location, yearStart) values (275, 'Karlstad', 1993);
insert into Branch (id, location, yearStart) values (276, 'Dziergowice', 2000);
insert into Branch (id, location, yearStart) values (277, 'Baidoa', 2009);
insert into Branch (id, location, yearStart) values (278, 'Uddevalla', 2007);
insert into Branch (id, location, yearStart) values (279, 'Xintang', 1999);
insert into Branch (id, location, yearStart) values (280, 'Memphis', 2001);
insert into Branch (id, location, yearStart) values (281, 'Metapán', 2000);
insert into Branch (id, location, yearStart) values (282, 'Shuanghe', 1994);
insert into Branch (id, location, yearStart) values (283, 'Zhanjiang', 2001);
insert into Branch (id, location, yearStart) values (284, 'Klevan’', 2011);
insert into Branch (id, location, yearStart) values (285, 'Aş Şalw', 2000);
insert into Branch (id, location, yearStart) values (286, 'El Paso', 1987);
insert into Branch (id, location, yearStart) values (287, 'Otra Banda', 2004);
insert into Branch (id, location, yearStart) values (288, 'Skutskär', 1995);
insert into Branch (id, location, yearStart) values (289, 'Palaiomonástiron', 2002);
insert into Branch (id, location, yearStart) values (290, 'Knjazevac', 2013);
insert into Branch (id, location, yearStart) values (291, 'Dushanbe', 1987);
insert into Branch (id, location, yearStart) values (292, 'Kitami', 2011);
insert into Branch (id, location, yearStart) values (293, 'Kezileboyi', 2013);
insert into Branch (id, location, yearStart) values (294, 'Malkā', 2008);
insert into Branch (id, location, yearStart) values (295, 'Al Ghayl', 2008);
insert into Branch (id, location, yearStart) values (296, 'Gununglarang', 1998);
insert into Branch (id, location, yearStart) values (297, 'Yanglin', 1995);
insert into Branch (id, location, yearStart) values (298, 'Baykalovo', 1997);
insert into Branch (id, location, yearStart) values (299, 'Hantai', 2012);
insert into Branch (id, location, yearStart) values (300, 'El Refugio', 2005);
insert into Branch (id, location, yearStart) values (301, 'Susuman', 2010);
insert into Branch (id, location, yearStart) values (302, 'Estoi', 1992);
insert into Branch (id, location, yearStart) values (303, 'Bang Racham', 2009);
insert into Branch (id, location, yearStart) values (304, 'Chahannao', 2010);
insert into Branch (id, location, yearStart) values (305, 'Vällingby', 2004);
insert into Branch (id, location, yearStart) values (306, 'Bedford', 2009);
insert into Branch (id, location, yearStart) values (307, 'Aracaju', 2012);
insert into Branch (id, location, yearStart) values (308, 'Manassas', 2011);
insert into Branch (id, location, yearStart) values (309, 'Terneuzen', 2008);
insert into Branch (id, location, yearStart) values (310, 'Kiruru', 2007);
insert into Branch (id, location, yearStart) values (311, 'San Rafael', 2009);
insert into Branch (id, location, yearStart) values (312, 'Toufang', 2005);
insert into Branch (id, location, yearStart) values (313, 'Coronel Fabriciano', 2009);
insert into Branch (id, location, yearStart) values (314, 'Magnitogorsk', 2007);
insert into Branch (id, location, yearStart) values (315, 'Jadho', 1992);
insert into Branch (id, location, yearStart) values (316, 'Carolina', 1986);
insert into Branch (id, location, yearStart) values (317, 'Oxelösund', 1991);
insert into Branch (id, location, yearStart) values (318, 'Puerto Ayacucho', 2009);
insert into Branch (id, location, yearStart) values (319, 'Otyń', 2012);
insert into Branch (id, location, yearStart) values (320, 'Aradac', 2006);
insert into Branch (id, location, yearStart) values (321, 'Nefta', 1999);
insert into Branch (id, location, yearStart) values (322, 'Melita', 1993);
insert into Branch (id, location, yearStart) values (323, 'Tournavista', 1993);
insert into Branch (id, location, yearStart) values (324, 'Gaoshan', 2003);
insert into Branch (id, location, yearStart) values (325, 'Petaling Jaya', 2009);
insert into Branch (id, location, yearStart) values (326, 'Kangxung', 1999);
insert into Branch (id, location, yearStart) values (327, 'Pingba', 2007);
insert into Branch (id, location, yearStart) values (328, 'Estaca', 2000);
insert into Branch (id, location, yearStart) values (329, 'Dianfang', 2008);
insert into Branch (id, location, yearStart) values (330, 'Sanshengyuan', 1992);
insert into Branch (id, location, yearStart) values (331, 'Qingping', 2005);
insert into Branch (id, location, yearStart) values (332, 'Alcoutim', 1994);
insert into Branch (id, location, yearStart) values (333, 'Virolahti', 2002);
insert into Branch (id, location, yearStart) values (334, 'Cambridge', 2008);
insert into Branch (id, location, yearStart) values (335, 'Antagan Segunda', 2012);
insert into Branch (id, location, yearStart) values (336, 'Aurora', 1988);
insert into Branch (id, location, yearStart) values (337, 'Erjiegou', 2009);
insert into Branch (id, location, yearStart) values (338, 'Quỳ Châu', 1998);
insert into Branch (id, location, yearStart) values (339, 'Getengan', 2003);
insert into Branch (id, location, yearStart) values (340, 'Tengger', 2010);
insert into Branch (id, location, yearStart) values (341, 'Pingpu', 2012);
insert into Branch (id, location, yearStart) values (342, 'Albarraque', 1998);
insert into Branch (id, location, yearStart) values (343, 'Beicheng', 2013);
insert into Branch (id, location, yearStart) values (344, 'Dalsjöfors', 2002);
insert into Branch (id, location, yearStart) values (345, 'Hobaramachi', 2005);
insert into Branch (id, location, yearStart) values (346, 'Ankazoabo', 2001);
insert into Branch (id, location, yearStart) values (347, 'Martigues', 2012);
insert into Branch (id, location, yearStart) values (348, 'Gemuruh', 2012);
insert into Branch (id, location, yearStart) values (349, 'San Isidro', 2000);
insert into Branch (id, location, yearStart) values (350, 'Emiliano Zapata', 1998);
insert into Branch (id, location, yearStart) values (351, 'Malambo', 2011);
insert into Branch (id, location, yearStart) values (352, 'Xilópolis', 1996);
insert into Branch (id, location, yearStart) values (353, 'Tegalgede', 2008);
insert into Branch (id, location, yearStart) values (354, 'Panorama', 2008);
insert into Branch (id, location, yearStart) values (355, 'Stockholm', 2005);
insert into Branch (id, location, yearStart) values (356, 'Liuhou', 2000);
insert into Branch (id, location, yearStart) values (357, 'Yuecheng', 1984);
insert into Branch (id, location, yearStart) values (358, 'Fenshui', 1985);
insert into Branch (id, location, yearStart) values (359, 'Valongo', 2009);
insert into Branch (id, location, yearStart) values (360, 'Siguqiao', 1997);
insert into Branch (id, location, yearStart) values (361, 'Erdao', 2008);
insert into Branch (id, location, yearStart) values (362, 'Zhangzhu', 2001);
insert into Branch (id, location, yearStart) values (363, 'Bárrio', 2002);
insert into Branch (id, location, yearStart) values (364, 'Estombar', 2006);
insert into Branch (id, location, yearStart) values (365, 'Poretskoye', 2003);
insert into Branch (id, location, yearStart) values (366, 'Daguo', 1956);
insert into Branch (id, location, yearStart) values (367, 'Shchëkino', 1990);
insert into Branch (id, location, yearStart) values (368, 'Iza', 1986);
insert into Branch (id, location, yearStart) values (369, 'Hadāli', 2006);
insert into Branch (id, location, yearStart) values (370, 'Hebian', 2004);
insert into Branch (id, location, yearStart) values (371, 'Monte-Carlo', 2013);
insert into Branch (id, location, yearStart) values (372, 'Jiantianjie', 1994);
insert into Branch (id, location, yearStart) values (373, 'Krajan Puru', 2002);
insert into Branch (id, location, yearStart) values (374, 'Jamaica', 2006);
insert into Branch (id, location, yearStart) values (375, 'Janeng', 2004);
insert into Branch (id, location, yearStart) values (376, 'Kafr Şaqr', 2010);
insert into Branch (id, location, yearStart) values (377, 'Resende', 2003);
insert into Branch (id, location, yearStart) values (378, 'Nabunturan', 2001);
insert into Branch (id, location, yearStart) values (379, 'Nizui', 2004);
insert into Branch (id, location, yearStart) values (380, 'Tabalong', 2006);
insert into Branch (id, location, yearStart) values (381, 'Tahara', 2001);
insert into Branch (id, location, yearStart) values (382, 'Rawawilis', 2001);
insert into Branch (id, location, yearStart) values (383, 'Waishan', 2013);
insert into Branch (id, location, yearStart) values (384, 'Kunting', 1999);
insert into Branch (id, location, yearStart) values (385, 'Beselga', 2009);
insert into Branch (id, location, yearStart) values (386, 'Catujal Velho', 2001);
insert into Branch (id, location, yearStart) values (387, 'Aihua', 1981);
insert into Branch (id, location, yearStart) values (388, 'Budakovo', 2012);
insert into Branch (id, location, yearStart) values (389, 'Bafatá', 2000);
insert into Branch (id, location, yearStart) values (390, 'Pardelhas', 1992);
insert into Branch (id, location, yearStart) values (391, 'Gaide', 2010);
insert into Branch (id, location, yearStart) values (392, 'Shuangjiang', 2003);
insert into Branch (id, location, yearStart) values (393, 'Kuncen', 1998);
insert into Branch (id, location, yearStart) values (394, 'Ndwedwe', 2005);
insert into Branch (id, location, yearStart) values (395, 'Ciguha Tengah', 1986);
insert into Branch (id, location, yearStart) values (396, 'Palmeira', 1997);
insert into Branch (id, location, yearStart) values (397, 'Penisihan', 2008);
insert into Branch (id, location, yearStart) values (398, 'Oneop', 2007);
insert into Branch (id, location, yearStart) values (399, 'Novo-Nikol’skoye', 1999);
insert into Branch (id, location, yearStart) values (400, 'Ueda', 2010);
insert into Branch (id, location, yearStart) values (401, 'Insrom', 1996);
insert into Branch (id, location, yearStart) values (402, 'Depapre', 2001);
insert into Branch (id, location, yearStart) values (403, 'Cibeureum', 2005);
insert into Branch (id, location, yearStart) values (404, 'Monte Patria', 2010);
insert into Branch (id, location, yearStart) values (405, 'Bandong', 2000);
insert into Branch (id, location, yearStart) values (406, 'Freiburg im Breisgau', 2000);
insert into Branch (id, location, yearStart) values (407, 'Tsyelyakhany', 2010);
insert into Branch (id, location, yearStart) values (408, 'Grenoble', 2004);
insert into Branch (id, location, yearStart) values (409, 'Remas', 2004);
insert into Branch (id, location, yearStart) values (410, 'Jingnao', 1991);
insert into Branch (id, location, yearStart) values (411, 'Lugo', 2004);
insert into Branch (id, location, yearStart) values (412, 'Pregonero', 2004);
insert into Branch (id, location, yearStart) values (413, 'Oslo', 2002);
insert into Branch (id, location, yearStart) values (414, 'Revda', 1995);
insert into Branch (id, location, yearStart) values (415, 'Maipú', 1999);
insert into Branch (id, location, yearStart) values (416, 'Khenifra', 2001);
insert into Branch (id, location, yearStart) values (417, 'Satte', 1997);
insert into Branch (id, location, yearStart) values (418, 'Surazh', 1994);
insert into Branch (id, location, yearStart) values (419, 'Shuangxi', 2010);
insert into Branch (id, location, yearStart) values (420, 'Jacksonville', 2009);
insert into Branch (id, location, yearStart) values (421, 'Banī Mazār', 1991);
insert into Branch (id, location, yearStart) values (422, 'Boa Vista', 1993);
insert into Branch (id, location, yearStart) values (423, 'Novo-Nikol’skoye', 2006);
insert into Branch (id, location, yearStart) values (424, 'Seoul', 2011);
insert into Branch (id, location, yearStart) values (425, 'Lis', 2000);
insert into Branch (id, location, yearStart) values (426, 'Abreu e Lima', 2006);
insert into Branch (id, location, yearStart) values (427, 'Kuršumlija', 2007);
insert into Branch (id, location, yearStart) values (428, 'Cigalontang', 2002);
insert into Branch (id, location, yearStart) values (429, 'Chiba', 2001);
insert into Branch (id, location, yearStart) values (430, 'Saint Joseph', 1997);
insert into Branch (id, location, yearStart) values (431, 'Nigríta', 2000);
insert into Branch (id, location, yearStart) values (432, 'Hongshan', 2011);
insert into Branch (id, location, yearStart) values (433, 'Ronov nad Doubravou', 2001);
insert into Branch (id, location, yearStart) values (434, 'Kemil', 1989);
insert into Branch (id, location, yearStart) values (435, 'Västerås', 1995);
insert into Branch (id, location, yearStart) values (436, 'Habiganj', 1993);
insert into Branch (id, location, yearStart) values (437, 'Wailiang', 1967);
insert into Branch (id, location, yearStart) values (438, 'Ábrego', 1995);
insert into Branch (id, location, yearStart) values (439, 'Gagarin', 2002);
insert into Branch (id, location, yearStart) values (440, 'Ban Mo', 1999);
insert into Branch (id, location, yearStart) values (441, 'Kostyantynivka', 2011);
insert into Branch (id, location, yearStart) values (442, 'Okigwi', 1992);
insert into Branch (id, location, yearStart) values (443, 'Larache', 1987);
insert into Branch (id, location, yearStart) values (444, 'Longtan', 1993);
insert into Branch (id, location, yearStart) values (445, 'José de Freitas', 2008);
insert into Branch (id, location, yearStart) values (446, 'Argenteuil', 2010);
insert into Branch (id, location, yearStart) values (447, 'Futaleufú', 2007);
insert into Branch (id, location, yearStart) values (448, 'Ancol', 1999);
insert into Branch (id, location, yearStart) values (449, 'Huanglian', 2010);
insert into Branch (id, location, yearStart) values (450, 'Buri', 2002);
insert into Branch (id, location, yearStart) values (451, 'San Antonio Oeste', 2002);
insert into Branch (id, location, yearStart) values (452, 'El Alto', 2005);
insert into Branch (id, location, yearStart) values (453, 'Amman', 2011);
insert into Branch (id, location, yearStart) values (454, 'Khuzhir', 2007);
insert into Branch (id, location, yearStart) values (455, 'Rudnichnyy', 1995);
insert into Branch (id, location, yearStart) values (456, 'Almafuerte', 2007);
insert into Branch (id, location, yearStart) values (457, 'Старо Нагоричане', 1995);
insert into Branch (id, location, yearStart) values (458, 'New Washington', 2004);
insert into Branch (id, location, yearStart) values (459, 'Cipadung Timur', 2011);
insert into Branch (id, location, yearStart) values (460, 'Da’an', 2003);
insert into Branch (id, location, yearStart) values (461, 'Pinggirsari', 1998);
insert into Branch (id, location, yearStart) values (462, 'Columbia', 2008);
insert into Branch (id, location, yearStart) values (463, 'Mingguang', 1999);
insert into Branch (id, location, yearStart) values (464, 'Pandanrejokrajan', 1995);
insert into Branch (id, location, yearStart) values (465, 'Ludvika', 2011);
insert into Branch (id, location, yearStart) values (466, 'San Martín Zapotitlán', 1990);
insert into Branch (id, location, yearStart) values (467, 'Komorniki', 1992);
insert into Branch (id, location, yearStart) values (468, 'Krajan Waturoyo', 2010);
insert into Branch (id, location, yearStart) values (469, 'Albina', 1995);
insert into Branch (id, location, yearStart) values (470, 'Pesagen', 1990);
insert into Branch (id, location, yearStart) values (471, 'Lantang', 2012);
insert into Branch (id, location, yearStart) values (472, 'Huangmao', 2005);
insert into Branch (id, location, yearStart) values (473, 'Bojonghaur', 1995);
insert into Branch (id, location, yearStart) values (474, 'Agen', 2004);
insert into Branch (id, location, yearStart) values (475, 'Liulin', 2003);
insert into Branch (id, location, yearStart) values (476, 'Léchovo', 2003);
insert into Branch (id, location, yearStart) values (477, 'Port Barton', 2006);
insert into Branch (id, location, yearStart) values (478, 'Sāqayn', 2010);
insert into Branch (id, location, yearStart) values (479, 'Kuala Terengganu', 1999);
insert into Branch (id, location, yearStart) values (480, 'Al Khushnīyah', 2012);
insert into Branch (id, location, yearStart) values (481, 'Tete', 1995);
insert into Branch (id, location, yearStart) values (482, 'Talacogon', 2010);
insert into Branch (id, location, yearStart) values (483, 'Longgang', 2010);
insert into Branch (id, location, yearStart) values (484, 'Shiniu', 1984);
insert into Branch (id, location, yearStart) values (485, 'Vällingby', 1990);
insert into Branch (id, location, yearStart) values (486, 'Yanagawa', 1997);
insert into Branch (id, location, yearStart) values (487, 'Citampian', 1995);
insert into Branch (id, location, yearStart) values (488, 'Wiang Chiang Rung', 2012);
insert into Branch (id, location, yearStart) values (489, 'Daliciasao', 1995);
insert into Branch (id, location, yearStart) values (490, 'Timurlorong', 2005);
insert into Branch (id, location, yearStart) values (491, 'Lewobelek', 2009);
insert into Branch (id, location, yearStart) values (492, 'Meedhoo', 2002);
insert into Branch (id, location, yearStart) values (493, 'Banjar Buahan', 2010);
insert into Branch (id, location, yearStart) values (494, 'San Carlos', 1995);
insert into Branch (id, location, yearStart) values (495, 'Babakansalam', 1993);
insert into Branch (id, location, yearStart) values (496, 'Stockholm', 2010);
insert into Branch (id, location, yearStart) values (497, 'Skalánion', 1994);
insert into Branch (id, location, yearStart) values (498, 'Jepat Kidul', 1995);
insert into Branch (id, location, yearStart) values (499, 'Wenchang', 2004);
insert into Branch (id, location, yearStart) values (500, 'Gurbuki', 2005);
insert into Branch (id, location, yearStart) values (501, 'Balogo', 1992);
insert into Branch (id, location, yearStart) values (502, 'Kupu', 2005);
insert into Branch (id, location, yearStart) values (503, 'Emmen', 1986);
insert into Branch (id, location, yearStart) values (504, 'Saint George''s', 2011);
insert into Branch (id, location, yearStart) values (505, 'Obikiik', 2008);
insert into Branch (id, location, yearStart) values (506, 'Skórcz', 2011);
insert into Branch (id, location, yearStart) values (507, 'Tapiramutá', 2006);
insert into Branch (id, location, yearStart) values (508, 'Mabyan', 1999);
insert into Branch (id, location, yearStart) values (509, 'Teresa', 2009);
insert into Branch (id, location, yearStart) values (510, 'Chīchāwatni', 2002);
insert into Branch (id, location, yearStart) values (511, 'Little Baguio', 2003);
insert into Branch (id, location, yearStart) values (512, 'Carrefour', 2003);
insert into Branch (id, location, yearStart) values (513, 'Baro', 1995);
insert into Branch (id, location, yearStart) values (514, 'Kurortnyy', 1999);
insert into Branch (id, location, yearStart) values (515, 'Huacheng', 2002);
insert into Branch (id, location, yearStart) values (516, 'Rudnichnyy', 2010);
insert into Branch (id, location, yearStart) values (517, 'Mirsíni', 2008);
insert into Branch (id, location, yearStart) values (518, 'Jiuxian', 1993);
insert into Branch (id, location, yearStart) values (519, 'Santiago De Compostela', 1992);
insert into Branch (id, location, yearStart) values (520, 'Kafyr-Kumukh', 2005);
insert into Branch (id, location, yearStart) values (521, 'Želešice', 2002);
insert into Branch (id, location, yearStart) values (522, 'El Monte', 1996);
insert into Branch (id, location, yearStart) values (523, 'Songkar B', 1992);
insert into Branch (id, location, yearStart) values (524, 'Nanterre', 1996);
insert into Branch (id, location, yearStart) values (525, 'Iwase', 2009);
insert into Branch (id, location, yearStart) values (526, 'Tarariras', 1983);
insert into Branch (id, location, yearStart) values (527, 'Nida', 1992);
insert into Branch (id, location, yearStart) values (528, 'Youssoufia', 1985);
insert into Branch (id, location, yearStart) values (529, 'Dąbrowa', 1995);
insert into Branch (id, location, yearStart) values (530, 'Guolemude', 1978);
insert into Branch (id, location, yearStart) values (531, 'Lipie', 1995);
insert into Branch (id, location, yearStart) values (532, 'Oslo', 2010);
insert into Branch (id, location, yearStart) values (533, 'Santo Domingo', 2004);
insert into Branch (id, location, yearStart) values (534, 'Vlachovice', 2003);
insert into Branch (id, location, yearStart) values (535, 'San Nicolas', 1978);
insert into Branch (id, location, yearStart) values (536, 'Prantaan', 2007);
insert into Branch (id, location, yearStart) values (537, 'Chicheng', 1995);
insert into Branch (id, location, yearStart) values (538, 'Tuqiao', 1988);
insert into Branch (id, location, yearStart) values (539, 'Guilhabreu', 2006);
insert into Branch (id, location, yearStart) values (540, 'Xiangzhu', 2006);
insert into Branch (id, location, yearStart) values (541, 'Atiquizaya', 1994);
insert into Branch (id, location, yearStart) values (542, 'Pembuanghulu', 2003);
insert into Branch (id, location, yearStart) values (543, 'Marau', 1998);
insert into Branch (id, location, yearStart) values (544, 'Corpus', 1989);
insert into Branch (id, location, yearStart) values (545, 'Wadungasri', 2008);
insert into Branch (id, location, yearStart) values (546, 'Nova Friburgo', 2002);
insert into Branch (id, location, yearStart) values (547, 'Camrose', 1990);
insert into Branch (id, location, yearStart) values (548, 'Al Hāshimīyah', 1999);
insert into Branch (id, location, yearStart) values (549, 'Dhī as Sufāl', 1997);
insert into Branch (id, location, yearStart) values (550, 'New York City', 2009);
insert into Branch (id, location, yearStart) values (551, 'Ghayl Bā Wazīr', 2010);
insert into Branch (id, location, yearStart) values (552, 'Harstad', 2008);
insert into Branch (id, location, yearStart) values (553, 'Badian', 1997);
insert into Branch (id, location, yearStart) values (554, 'Matam', 1999);
insert into Branch (id, location, yearStart) values (555, 'Jampang Tengah', 2009);
insert into Branch (id, location, yearStart) values (556, 'Krasnogorskoye', 2012);
insert into Branch (id, location, yearStart) values (557, 'Fresno', 2005);
insert into Branch (id, location, yearStart) values (558, 'Aglipay', 2008);
insert into Branch (id, location, yearStart) values (559, 'Sancha', 2001);
insert into Branch (id, location, yearStart) values (560, 'Mancilang', 2000);
insert into Branch (id, location, yearStart) values (561, 'Corbeil-Essonnes', 1995);
insert into Branch (id, location, yearStart) values (562, 'Yandun', 2003);
insert into Branch (id, location, yearStart) values (563, 'Lixi', 1993);
insert into Branch (id, location, yearStart) values (564, 'Jiasi', 2003);
insert into Branch (id, location, yearStart) values (565, 'Gagarawa', 1995);
insert into Branch (id, location, yearStart) values (566, 'Bekondo', 2008);
insert into Branch (id, location, yearStart) values (567, 'Şabrātah', 2002);
insert into Branch (id, location, yearStart) values (568, 'Prado Siongco', 2009);
insert into Branch (id, location, yearStart) values (569, 'Khlong Toei', 1991);
insert into Branch (id, location, yearStart) values (570, 'Al Jīb', 2012);
insert into Branch (id, location, yearStart) values (571, 'Cerrito', 2011);
insert into Branch (id, location, yearStart) values (572, 'Jakartovice', 2006);
insert into Branch (id, location, yearStart) values (573, 'Tangxi', 2008);
insert into Branch (id, location, yearStart) values (574, 'Yingjiang', 1991);
insert into Branch (id, location, yearStart) values (575, 'Magrath', 1998);
insert into Branch (id, location, yearStart) values (576, 'Bayt ‘Adhāqah', 1989);
insert into Branch (id, location, yearStart) values (577, 'Pasuruan', 1993);
insert into Branch (id, location, yearStart) values (578, 'La Plata', 2004);
insert into Branch (id, location, yearStart) values (579, 'Yangdenghu', 1999);
insert into Branch (id, location, yearStart) values (580, 'Nova Olímpia', 2009);
insert into Branch (id, location, yearStart) values (581, 'Kuala Lumpur', 1996);
insert into Branch (id, location, yearStart) values (582, 'Khairpur', 2010);
insert into Branch (id, location, yearStart) values (583, 'Portland', 2004);
insert into Branch (id, location, yearStart) values (584, 'Kukës', 2013);
insert into Branch (id, location, yearStart) values (585, 'Saint-Denis', 2002);
insert into Branch (id, location, yearStart) values (586, 'Courtaboeuf', 2005);
insert into Branch (id, location, yearStart) values (587, 'Panamá', 2007);
insert into Branch (id, location, yearStart) values (588, 'Wangcao', 2004);
insert into Branch (id, location, yearStart) values (589, 'Ḩātim', 1992);
insert into Branch (id, location, yearStart) values (590, 'Karangbayat', 2006);
insert into Branch (id, location, yearStart) values (591, 'Wulan', 1996);
insert into Branch (id, location, yearStart) values (592, 'Dagur', 2010);
insert into Branch (id, location, yearStart) values (593, 'San Roque', 1996);
insert into Branch (id, location, yearStart) values (594, 'Montceau-les-Mines', 1967);
insert into Branch (id, location, yearStart) values (595, 'Bila Krynytsya', 1986);
insert into Branch (id, location, yearStart) values (596, 'Pando', 1961);
insert into Branch (id, location, yearStart) values (597, 'Čačak', 1991);
insert into Branch (id, location, yearStart) values (598, 'Guapi', 1995);
insert into Branch (id, location, yearStart) values (599, 'Wangsi', 1998);
insert into Branch (id, location, yearStart) values (600, 'Huangyang', 2011);
insert into Branch (id, location, yearStart) values (601, 'Fujinomiya', 2002);
insert into Branch (id, location, yearStart) values (602, 'Imeni Babushkina', 1995);
insert into Branch (id, location, yearStart) values (603, 'Yejia', 2010);
insert into Branch (id, location, yearStart) values (604, 'Romanovo', 2003);
insert into Branch (id, location, yearStart) values (605, 'Kukichūō', 2011);
insert into Branch (id, location, yearStart) values (606, 'Sheregesh', 1998);
insert into Branch (id, location, yearStart) values (607, 'Curitibanos', 1998);
insert into Branch (id, location, yearStart) values (608, 'Paprotnia', 2011);
insert into Branch (id, location, yearStart) values (609, 'Alenquer', 1984);
insert into Branch (id, location, yearStart) values (610, 'Huangling', 1993);
insert into Branch (id, location, yearStart) values (611, 'Haurpanggung', 2005);
insert into Branch (id, location, yearStart) values (612, 'eMbalenhle', 2013);
insert into Branch (id, location, yearStart) values (613, 'Pontinha', 1998);
insert into Branch (id, location, yearStart) values (614, 'Safonovo', 1991);
insert into Branch (id, location, yearStart) values (615, 'Machinda', 1998);
insert into Branch (id, location, yearStart) values (616, 'Wangsi', 2007);
insert into Branch (id, location, yearStart) values (617, 'Jimaguayú', 2012);
insert into Branch (id, location, yearStart) values (618, 'Luzhi', 2011);
insert into Branch (id, location, yearStart) values (619, 'Frakulla e Madhe', 2008);
insert into Branch (id, location, yearStart) values (620, 'Grybów', 1995);
insert into Branch (id, location, yearStart) values (621, 'Quime', 2011);
insert into Branch (id, location, yearStart) values (622, 'Troitskoye', 2009);
insert into Branch (id, location, yearStart) values (623, 'Tarangnan', 2010);
insert into Branch (id, location, yearStart) values (624, 'Thị Trấn Tam Sơn', 1987);
insert into Branch (id, location, yearStart) values (625, 'Chowki Jamali', 1996);
insert into Branch (id, location, yearStart) values (626, 'Kolumbug', 1974);
insert into Branch (id, location, yearStart) values (627, 'Gongping', 1986);
insert into Branch (id, location, yearStart) values (628, 'Xinglong', 1999);
insert into Branch (id, location, yearStart) values (629, 'Uluale', 1988);
insert into Branch (id, location, yearStart) values (630, 'Satka', 1996);
insert into Branch (id, location, yearStart) values (631, 'Kajatian', 1993);
insert into Branch (id, location, yearStart) values (632, 'Lebane', 2006);
insert into Branch (id, location, yearStart) values (633, 'Chicago', 2009);
insert into Branch (id, location, yearStart) values (634, 'Mtambile', 2007);
insert into Branch (id, location, yearStart) values (635, 'Wuma', 2006);
insert into Branch (id, location, yearStart) values (636, 'Gvozd', 1999);
insert into Branch (id, location, yearStart) values (637, 'Hiroshima-shi', 2006);
insert into Branch (id, location, yearStart) values (638, 'Ortega', 1960);
insert into Branch (id, location, yearStart) values (639, 'Piñas', 1997);
insert into Branch (id, location, yearStart) values (640, 'Hekou', 2006);
insert into Branch (id, location, yearStart) values (641, 'Örebro', 1996);
insert into Branch (id, location, yearStart) values (642, 'Dolod', 1987);
insert into Branch (id, location, yearStart) values (643, 'Cabugao', 1998);
insert into Branch (id, location, yearStart) values (644, 'Jönköping', 2010);
insert into Branch (id, location, yearStart) values (645, 'Lubrza', 1985);
insert into Branch (id, location, yearStart) values (646, 'Mejdan - Obilićevo', 2005);
insert into Branch (id, location, yearStart) values (647, 'Isfara', 2001);
insert into Branch (id, location, yearStart) values (648, 'Miura', 2002);
insert into Branch (id, location, yearStart) values (649, 'Jefferson City', 2004);
insert into Branch (id, location, yearStart) values (650, 'Sorinomo', 2008);
insert into Branch (id, location, yearStart) values (651, 'Praia', 1988);
insert into Branch (id, location, yearStart) values (652, 'Condado', 1996);
insert into Branch (id, location, yearStart) values (653, 'Drásov', 2012);
insert into Branch (id, location, yearStart) values (654, 'Caraballeda', 2009);
insert into Branch (id, location, yearStart) values (655, 'Bochum', 2008);
insert into Branch (id, location, yearStart) values (656, 'Zarszyn', 2008);
insert into Branch (id, location, yearStart) values (657, 'Čelinac', 1991);
insert into Branch (id, location, yearStart) values (658, 'Imeni Tsyurupy', 1998);
insert into Branch (id, location, yearStart) values (659, 'Chitré', 2011);
insert into Branch (id, location, yearStart) values (660, 'Odemira', 2001);
insert into Branch (id, location, yearStart) values (661, 'Johor Bahru', 2007);
insert into Branch (id, location, yearStart) values (662, 'Karangduren Dua', 1992);
insert into Branch (id, location, yearStart) values (663, 'Canta', 1994);
insert into Branch (id, location, yearStart) values (664, 'Kazanlŭk', 2006);
insert into Branch (id, location, yearStart) values (665, 'Puget-sur-Argens', 1995);
insert into Branch (id, location, yearStart) values (666, 'Maciejowice', 2005);
insert into Branch (id, location, yearStart) values (667, 'Sabnova', 1996);
insert into Branch (id, location, yearStart) values (668, 'Tiarei', 2010);
insert into Branch (id, location, yearStart) values (669, 'Nal’chik', 2007);
insert into Branch (id, location, yearStart) values (670, 'Évry', 2009);
insert into Branch (id, location, yearStart) values (671, 'San Jacinto', 1988);
insert into Branch (id, location, yearStart) values (672, 'Káto Nevrokópi', 2003);
insert into Branch (id, location, yearStart) values (673, 'Santana', 2004);
insert into Branch (id, location, yearStart) values (674, 'Khandagayty', 2004);
insert into Branch (id, location, yearStart) values (675, 'Greda', 2012);
insert into Branch (id, location, yearStart) values (676, 'Watulumbung', 1997);
insert into Branch (id, location, yearStart) values (677, 'Oslo', 2012);
insert into Branch (id, location, yearStart) values (678, 'Mananjary', 2008);
insert into Branch (id, location, yearStart) values (679, 'Koniaków', 2011);
insert into Branch (id, location, yearStart) values (680, 'Bat Khela', 1993);
insert into Branch (id, location, yearStart) values (681, 'Tianjiazhai', 1987);
insert into Branch (id, location, yearStart) values (682, 'Aranđelovac', 2003);
insert into Branch (id, location, yearStart) values (683, 'Yuanyang', 2008);
insert into Branch (id, location, yearStart) values (684, 'Ajung', 2010);
insert into Branch (id, location, yearStart) values (685, 'Carmo do Paranaíba', 2010);
insert into Branch (id, location, yearStart) values (686, 'Binubusan', 2004);
insert into Branch (id, location, yearStart) values (687, 'Cortes', 2013);
insert into Branch (id, location, yearStart) values (688, 'Zeist', 1994);
insert into Branch (id, location, yearStart) values (689, 'Toledo', 2005);
insert into Branch (id, location, yearStart) values (690, 'Bābolsar', 2004);
insert into Branch (id, location, yearStart) values (691, 'Tanumshede', 2003);
insert into Branch (id, location, yearStart) values (692, 'Machico', 2007);
insert into Branch (id, location, yearStart) values (693, 'Labuhan Deli', 2011);
insert into Branch (id, location, yearStart) values (694, 'Chaem Luang', 2012);
insert into Branch (id, location, yearStart) values (695, 'Châlons-en-Champagne', 1996);
insert into Branch (id, location, yearStart) values (696, 'Cầu Gồ', 2003);
insert into Branch (id, location, yearStart) values (697, 'Novonikol’sk', 2009);
insert into Branch (id, location, yearStart) values (698, 'Rada Tilly', 2012);
insert into Branch (id, location, yearStart) values (699, 'Borovlyany', 2011);
insert into Branch (id, location, yearStart) values (700, 'Camarate', 2009);
insert into Branch (id, location, yearStart) values (701, 'Luoshe', 1985);
insert into Branch (id, location, yearStart) values (702, 'Ocampo', 1988);
insert into Branch (id, location, yearStart) values (703, 'Winangun', 1996);
insert into Branch (id, location, yearStart) values (704, 'Jiaozuo', 1996);
insert into Branch (id, location, yearStart) values (705, 'Marathon', 2011);
insert into Branch (id, location, yearStart) values (706, 'Maceda', 2012);
insert into Branch (id, location, yearStart) values (707, 'Lingyuan', 1988);
insert into Branch (id, location, yearStart) values (708, 'Vermil', 2000);
insert into Branch (id, location, yearStart) values (709, 'Lang', 1998);
insert into Branch (id, location, yearStart) values (710, 'Montreuil', 1997);
insert into Branch (id, location, yearStart) values (711, 'Pandean', 1986);
insert into Branch (id, location, yearStart) values (712, 'Yixingfu', 1993);
insert into Branch (id, location, yearStart) values (713, 'Baturaja', 1992);
insert into Branch (id, location, yearStart) values (714, 'Líbeznice', 2002);
insert into Branch (id, location, yearStart) values (715, 'Hajeom', 1986);
insert into Branch (id, location, yearStart) values (716, 'Guataquí', 1998);
insert into Branch (id, location, yearStart) values (717, 'København', 2009);
insert into Branch (id, location, yearStart) values (718, 'Neryungri', 1992);
insert into Branch (id, location, yearStart) values (719, 'Tiepu', 1987);
insert into Branch (id, location, yearStart) values (720, 'Lensk', 2009);
insert into Branch (id, location, yearStart) values (721, 'Nový Malín', 1995);
insert into Branch (id, location, yearStart) values (722, 'São Pedro', 2008);
insert into Branch (id, location, yearStart) values (723, 'Dasha', 2010);
insert into Branch (id, location, yearStart) values (724, 'Kembangkerang Lauk Timur', 2011);
insert into Branch (id, location, yearStart) values (725, 'Gaohu', 1996);
insert into Branch (id, location, yearStart) values (726, 'Huaquillas', 1989);
insert into Branch (id, location, yearStart) values (727, 'Planaltina', 2005);
insert into Branch (id, location, yearStart) values (728, 'Radekhiv', 2003);
insert into Branch (id, location, yearStart) values (729, 'Baisangguan', 1998);
insert into Branch (id, location, yearStart) values (730, 'Horní Čermná', 1993);
insert into Branch (id, location, yearStart) values (731, 'Caramay', 1995);
insert into Branch (id, location, yearStart) values (732, 'Shajing', 1996);
insert into Branch (id, location, yearStart) values (733, 'Aga', 1999);
insert into Branch (id, location, yearStart) values (734, 'Sacramento', 2008);
insert into Branch (id, location, yearStart) values (735, 'Nankeng', 1987);
insert into Branch (id, location, yearStart) values (736, 'Igpit', 2012);
insert into Branch (id, location, yearStart) values (737, 'La Jicaral', 2000);
insert into Branch (id, location, yearStart) values (738, 'Longnawang', 2000);
insert into Branch (id, location, yearStart) values (739, 'Ayapel', 2010);
insert into Branch (id, location, yearStart) values (740, 'Ayna', 1998);
insert into Branch (id, location, yearStart) values (741, 'Niamtougou', 2003);
insert into Branch (id, location, yearStart) values (742, 'Longgang', 1999);
insert into Branch (id, location, yearStart) values (743, 'Longlisuo', 2002);
insert into Branch (id, location, yearStart) values (744, 'Sihe', 1995);
insert into Branch (id, location, yearStart) values (745, 'Wugong', 1992);
insert into Branch (id, location, yearStart) values (746, 'Yuxarı Aran', 2009);
insert into Branch (id, location, yearStart) values (747, 'Qiaoxia', 1999);
insert into Branch (id, location, yearStart) values (748, 'Didian', 2006);
insert into Branch (id, location, yearStart) values (749, 'Itéa', 1995);
insert into Branch (id, location, yearStart) values (750, 'Molsheim', 1988);
insert into Branch (id, location, yearStart) values (751, 'Issa', 2008);
insert into Branch (id, location, yearStart) values (752, 'Agbor', 2006);
insert into Branch (id, location, yearStart) values (753, 'Āl Ma‘ūdah', 2006);
insert into Branch (id, location, yearStart) values (754, 'Kihurio', 1998);
insert into Branch (id, location, yearStart) values (755, 'Flen', 2006);
insert into Branch (id, location, yearStart) values (756, 'Xiayang', 2010);
insert into Branch (id, location, yearStart) values (757, 'San Francisco', 1992);
insert into Branch (id, location, yearStart) values (758, 'Kladi', 2011);
insert into Branch (id, location, yearStart) values (759, 'Chunhua', 1993);
insert into Branch (id, location, yearStart) values (760, 'Ouyang', 1987);
insert into Branch (id, location, yearStart) values (761, 'Devon', 1994);
insert into Branch (id, location, yearStart) values (762, 'Cikulina', 2004);
insert into Branch (id, location, yearStart) values (763, 'Outeiro', 1996);
insert into Branch (id, location, yearStart) values (764, 'Zhoushan', 1994);
insert into Branch (id, location, yearStart) values (765, 'Mbanza Congo', 1999);
insert into Branch (id, location, yearStart) values (766, 'Qiulu', 2001);
insert into Branch (id, location, yearStart) values (767, 'Currais Novos', 1991);
insert into Branch (id, location, yearStart) values (768, 'Tipaz', 1992);
insert into Branch (id, location, yearStart) values (769, 'Báguanos', 1990);
insert into Branch (id, location, yearStart) values (770, 'Buynichy', 2001);
insert into Branch (id, location, yearStart) values (771, 'Ensanche Luperón', 2006);
insert into Branch (id, location, yearStart) values (772, 'Rawannawi Village', 2006);
insert into Branch (id, location, yearStart) values (773, 'Libofshë', 2002);
insert into Branch (id, location, yearStart) values (774, 'Santa Lucía', 1978);
insert into Branch (id, location, yearStart) values (775, 'Bastia', 1994);
insert into Branch (id, location, yearStart) values (776, 'Tékane', 1992);
insert into Branch (id, location, yearStart) values (777, 'Babice', 2010);
insert into Branch (id, location, yearStart) values (778, 'Ciudad Barrios', 1986);
insert into Branch (id, location, yearStart) values (779, 'Borås', 1987);
insert into Branch (id, location, yearStart) values (780, 'Njivice', 1991);
insert into Branch (id, location, yearStart) values (781, 'Lavadorinhos', 1999);
insert into Branch (id, location, yearStart) values (782, 'Kalloní', 1991);
insert into Branch (id, location, yearStart) values (783, 'Samsan', 2000);
insert into Branch (id, location, yearStart) values (784, 'Al Fashn', 1998);
insert into Branch (id, location, yearStart) values (785, 'Kuantan', 2010);
insert into Branch (id, location, yearStart) values (786, 'Jingxin', 2004);
insert into Branch (id, location, yearStart) values (787, 'Campo Quijano', 2006);
insert into Branch (id, location, yearStart) values (788, 'Ijuw', 2009);
insert into Branch (id, location, yearStart) values (789, 'San Diego', 2012);
insert into Branch (id, location, yearStart) values (790, 'Chhāgalnāiya', 1999);
insert into Branch (id, location, yearStart) values (791, 'Ochota', 1999);
insert into Branch (id, location, yearStart) values (792, 'Hrušovany u Brna', 2005);
insert into Branch (id, location, yearStart) values (793, 'Machang', 2006);
insert into Branch (id, location, yearStart) values (794, 'Xinjiezhen', 2004);
insert into Branch (id, location, yearStart) values (795, 'Titab', 2004);
insert into Branch (id, location, yearStart) values (796, 'Lumil', 2007);
insert into Branch (id, location, yearStart) values (797, 'San Francisco de Yare', 1994);
insert into Branch (id, location, yearStart) values (798, 'Amuñgan', 1990);
insert into Branch (id, location, yearStart) values (799, 'Kaliuda', 1998);
insert into Branch (id, location, yearStart) values (800, 'Kingston', 2008);
insert into Branch (id, location, yearStart) values (801, 'Bakungan', 1992);
insert into Branch (id, location, yearStart) values (802, 'San Miguel', 1990);
insert into Branch (id, location, yearStart) values (803, 'Argungu', 2003);
insert into Branch (id, location, yearStart) values (804, 'Linxi', 2006);
insert into Branch (id, location, yearStart) values (805, 'Maribong', 2008);
insert into Branch (id, location, yearStart) values (806, 'Planovskoye', 2004);
insert into Branch (id, location, yearStart) values (807, 'Kamwenge', 2010);
insert into Branch (id, location, yearStart) values (808, 'Wanglinkou', 2009);
insert into Branch (id, location, yearStart) values (809, 'Jiaobei', 1998);
insert into Branch (id, location, yearStart) values (810, 'Bangad', 2012);
insert into Branch (id, location, yearStart) values (811, 'Uusikaupunki', 2006);
insert into Branch (id, location, yearStart) values (812, 'Tak', 1996);
insert into Branch (id, location, yearStart) values (813, 'Rukungiri', 2000);
insert into Branch (id, location, yearStart) values (814, 'Fuding', 1986);
insert into Branch (id, location, yearStart) values (815, 'Maroa', 1992);
insert into Branch (id, location, yearStart) values (816, 'Xai-Xai', 1991);
insert into Branch (id, location, yearStart) values (817, 'Shihudang', 2011);
insert into Branch (id, location, yearStart) values (818, 'Bandeirantes', 2005);
insert into Branch (id, location, yearStart) values (819, 'Haokou', 1998);
insert into Branch (id, location, yearStart) values (820, 'Herceg-Novi', 2006);
insert into Branch (id, location, yearStart) values (821, 'Tongjiang', 2008);
insert into Branch (id, location, yearStart) values (822, 'Rennes', 1985);
insert into Branch (id, location, yearStart) values (823, 'Vacaria', 2005);
insert into Branch (id, location, yearStart) values (824, 'Talovyy', 2001);
insert into Branch (id, location, yearStart) values (825, 'Sousa', 1985);
insert into Branch (id, location, yearStart) values (826, 'Xiaojing', 2010);
insert into Branch (id, location, yearStart) values (827, 'Manghit', 1995);
insert into Branch (id, location, yearStart) values (828, 'Farsta', 1999);
insert into Branch (id, location, yearStart) values (829, 'São Miguel do Rio Torto', 1984);
insert into Branch (id, location, yearStart) values (830, 'Líbano', 2002);
insert into Branch (id, location, yearStart) values (831, 'Bayan Uula Sumu', 1999);
insert into Branch (id, location, yearStart) values (832, 'Jiufeng', 2011);
insert into Branch (id, location, yearStart) values (833, 'Ambarakaraka', 1994);
insert into Branch (id, location, yearStart) values (834, 'Wangdain', 2004);
insert into Branch (id, location, yearStart) values (835, 'Aráchova', 2003);
insert into Branch (id, location, yearStart) values (836, 'Australia Square', 1999);
insert into Branch (id, location, yearStart) values (837, 'Nakło nad Notecią', 2006);
insert into Branch (id, location, yearStart) values (838, 'Idrija', 2001);
insert into Branch (id, location, yearStart) values (839, 'Bao’an', 2004);
insert into Branch (id, location, yearStart) values (840, 'Laguilayan', 1993);
insert into Branch (id, location, yearStart) values (841, 'Huaiyuan Chengguanzhen', 2004);
insert into Branch (id, location, yearStart) values (842, 'Futtsu', 2005);
insert into Branch (id, location, yearStart) values (843, 'Songfeng', 2002);
insert into Branch (id, location, yearStart) values (844, 'Thị Trấn Pác Miầu', 1992);
insert into Branch (id, location, yearStart) values (845, 'Biao', 1995);
insert into Branch (id, location, yearStart) values (846, 'Hariang', 2009);
insert into Branch (id, location, yearStart) values (847, 'Asbestos', 2001);
insert into Branch (id, location, yearStart) values (848, 'Giesteira', 2007);
insert into Branch (id, location, yearStart) values (849, 'Pierreville', 1991);
insert into Branch (id, location, yearStart) values (850, 'Oster', 1994);
insert into Branch (id, location, yearStart) values (851, 'Shixiang', 2002);
insert into Branch (id, location, yearStart) values (852, 'Srostki', 2009);
insert into Branch (id, location, yearStart) values (853, 'Buang', 1988);
insert into Branch (id, location, yearStart) values (854, 'Jiaoyang', 1993);
insert into Branch (id, location, yearStart) values (855, 'Ripky', 2000);
insert into Branch (id, location, yearStart) values (856, 'Kępno', 1991);
insert into Branch (id, location, yearStart) values (857, 'Xijiang', 2007);
insert into Branch (id, location, yearStart) values (858, 'Manado', 2009);
insert into Branch (id, location, yearStart) values (859, 'Vrýses', 2002);
insert into Branch (id, location, yearStart) values (860, 'Las Palmas', 2002);
insert into Branch (id, location, yearStart) values (861, 'Tanzybey', 1997);
insert into Branch (id, location, yearStart) values (862, 'Nagosela', 2005);
insert into Branch (id, location, yearStart) values (863, 'Changqi', 2005);
insert into Branch (id, location, yearStart) values (864, 'Mogwase', 2010);
insert into Branch (id, location, yearStart) values (865, 'Saint-Rémi', 2012);
insert into Branch (id, location, yearStart) values (866, 'Núi Sập', 1988);
insert into Branch (id, location, yearStart) values (867, 'Hejiadong', 2009);
insert into Branch (id, location, yearStart) values (868, 'Annau', 1998);
insert into Branch (id, location, yearStart) values (869, 'Mīrpur Sakro', 2009);
insert into Branch (id, location, yearStart) values (870, 'Tongzilin', 2001);
insert into Branch (id, location, yearStart) values (871, 'Castro Daire', 2008);
insert into Branch (id, location, yearStart) values (872, 'Villa Yapacaní', 1998);
insert into Branch (id, location, yearStart) values (873, 'Valday', 2009);
insert into Branch (id, location, yearStart) values (874, 'Tabuaço', 1993);
insert into Branch (id, location, yearStart) values (875, 'Nicolas Bravo', 2012);
insert into Branch (id, location, yearStart) values (876, 'Calilegua', 1993);
insert into Branch (id, location, yearStart) values (877, 'Al Tuḩaytā’', 1971);
insert into Branch (id, location, yearStart) values (878, 'Wujiashan', 2010);
insert into Branch (id, location, yearStart) values (879, 'San Salvador', 2007);
insert into Branch (id, location, yearStart) values (880, 'Ocuviri', 2010);
insert into Branch (id, location, yearStart) values (881, 'Pajaten', 1987);
insert into Branch (id, location, yearStart) values (882, 'Ribeira Grande', 2009);
insert into Branch (id, location, yearStart) values (883, 'Alhos Vedros', 2005);
insert into Branch (id, location, yearStart) values (884, 'Mekarsari', 1999);
insert into Branch (id, location, yearStart) values (885, 'Thành Phố Phủ Lý', 1995);
insert into Branch (id, location, yearStart) values (886, 'Ballylinan', 1989);
insert into Branch (id, location, yearStart) values (887, 'Changbai', 2008);
insert into Branch (id, location, yearStart) values (888, 'Kebonkai', 2005);
insert into Branch (id, location, yearStart) values (889, 'Bisert’', 2009);
insert into Branch (id, location, yearStart) values (890, 'Alejo Ledesma', 1992);
insert into Branch (id, location, yearStart) values (891, 'Young', 1987);
insert into Branch (id, location, yearStart) values (892, 'Castainço', 2005);
insert into Branch (id, location, yearStart) values (893, 'Kristiansund N', 1994);
insert into Branch (id, location, yearStart) values (894, 'Dananyu', 1995);
insert into Branch (id, location, yearStart) values (895, 'Concepción de Ataco', 1996);
insert into Branch (id, location, yearStart) values (896, 'Banjar Budakeling', 1993);
insert into Branch (id, location, yearStart) values (897, 'Pervoavgustovskiy', 2001);
insert into Branch (id, location, yearStart) values (898, 'Aleysk', 1992);
insert into Branch (id, location, yearStart) values (899, 'Dimitrovgrad', 1988);
insert into Branch (id, location, yearStart) values (900, 'Yuanqian', 2008);
insert into Branch (id, location, yearStart) values (901, 'Habry', 1997);
insert into Branch (id, location, yearStart) values (902, 'Nanlü', 2008);
insert into Branch (id, location, yearStart) values (903, 'Demerval Lobão', 1993);
insert into Branch (id, location, yearStart) values (904, 'Campo Formoso', 1998);
insert into Branch (id, location, yearStart) values (905, 'Artemivs’k', 2007);
insert into Branch (id, location, yearStart) values (906, 'Baiyang', 1992);
insert into Branch (id, location, yearStart) values (907, 'Gaspar Hernández', 2001);
insert into Branch (id, location, yearStart) values (908, 'Vysotsk', 1992);
insert into Branch (id, location, yearStart) values (909, 'Chuhuyiv', 1990);
insert into Branch (id, location, yearStart) values (910, 'Nova Russas', 1998);
insert into Branch (id, location, yearStart) values (911, 'Mpulungu', 1995);
insert into Branch (id, location, yearStart) values (912, 'Gavarr', 1998);
insert into Branch (id, location, yearStart) values (913, 'Tigaon', 2004);
insert into Branch (id, location, yearStart) values (914, 'Buritizeiro', 1987);
insert into Branch (id, location, yearStart) values (915, 'Telagasari', 2006);
insert into Branch (id, location, yearStart) values (916, 'Tangzhuang', 2008);
insert into Branch (id, location, yearStart) values (917, 'Rinbung', 2003);
insert into Branch (id, location, yearStart) values (918, 'Osinniki', 1994);
insert into Branch (id, location, yearStart) values (919, 'El Peñol', 2005);
insert into Branch (id, location, yearStart) values (920, 'São Joaquim da Barra', 2008);
insert into Branch (id, location, yearStart) values (921, 'Dongguang', 2011);
insert into Branch (id, location, yearStart) values (922, 'Gniezno', 2009);
insert into Branch (id, location, yearStart) values (923, 'San Isidro', 2008);
insert into Branch (id, location, yearStart) values (924, 'Sakété', 1995);
insert into Branch (id, location, yearStart) values (925, 'Jatipamor', 2000);
insert into Branch (id, location, yearStart) values (926, 'Nova Era', 1994);
insert into Branch (id, location, yearStart) values (927, 'Cruzeiro', 1997);
insert into Branch (id, location, yearStart) values (928, 'Pasirgaru', 2001);
insert into Branch (id, location, yearStart) values (929, 'Stockholm', 2011);
insert into Branch (id, location, yearStart) values (930, 'Alpedrinha', 1992);
insert into Branch (id, location, yearStart) values (931, 'Palma De Mallorca', 1990);
insert into Branch (id, location, yearStart) values (932, 'Baiyang', 1984);
insert into Branch (id, location, yearStart) values (933, 'Český Těšín', 1987);
insert into Branch (id, location, yearStart) values (934, 'Looc', 2005);
insert into Branch (id, location, yearStart) values (935, 'Phra Phrom', 2000);
insert into Branch (id, location, yearStart) values (936, 'Simunul', 2007);
insert into Branch (id, location, yearStart) values (937, 'Kuafeu', 1997);
insert into Branch (id, location, yearStart) values (938, 'Arauá', 2012);
insert into Branch (id, location, yearStart) values (939, 'Manosque', 2012);
insert into Branch (id, location, yearStart) values (940, 'Taytayan', 1990);
insert into Branch (id, location, yearStart) values (941, 'Goranboy', 2008);
insert into Branch (id, location, yearStart) values (942, 'Kostino', 2009);
insert into Branch (id, location, yearStart) values (943, 'Canavieiras', 1994);
insert into Branch (id, location, yearStart) values (944, 'Ayapa', 1995);
insert into Branch (id, location, yearStart) values (945, 'Tairan Camp', 1993);
insert into Branch (id, location, yearStart) values (946, 'Pokrov', 2009);
insert into Branch (id, location, yearStart) values (947, 'Mohammedia', 2012);
insert into Branch (id, location, yearStart) values (948, 'Barinitas', 1998);
insert into Branch (id, location, yearStart) values (949, 'Huaikan', 1996);
insert into Branch (id, location, yearStart) values (950, 'Artimet', 2003);
insert into Branch (id, location, yearStart) values (951, 'Pizarrete', 2003);
insert into Branch (id, location, yearStart) values (952, 'Cachadinha', 2006);
insert into Branch (id, location, yearStart) values (953, 'Nagarakembang', 1996);
insert into Branch (id, location, yearStart) values (954, 'Palopat', 2009);
insert into Branch (id, location, yearStart) values (955, 'Studzionka', 2007);
insert into Branch (id, location, yearStart) values (956, 'Belyye Berega', 1966);
insert into Branch (id, location, yearStart) values (957, 'Sukodono', 1984);
insert into Branch (id, location, yearStart) values (958, 'Mayumba', 2003);
insert into Branch (id, location, yearStart) values (959, 'Vahdat', 2009);
insert into Branch (id, location, yearStart) values (960, 'Tomislavgrad', 2009);
insert into Branch (id, location, yearStart) values (961, 'Matango', 2009);
insert into Branch (id, location, yearStart) values (962, 'Nelipyno', 2010);
insert into Branch (id, location, yearStart) values (963, 'Augusta', 2010);
insert into Branch (id, location, yearStart) values (964, 'Kotadukuh', 1953);
insert into Branch (id, location, yearStart) values (965, 'Zhenlong', 1990);
insert into Branch (id, location, yearStart) values (966, 'Rzepiennik Strzyżewski', 2006);
insert into Branch (id, location, yearStart) values (967, 'Blois', 2010);
insert into Branch (id, location, yearStart) values (968, 'Yueyang', 2009);
insert into Branch (id, location, yearStart) values (969, 'Anambongan', 1989);
insert into Branch (id, location, yearStart) values (970, 'Kisasa', 2006);
insert into Branch (id, location, yearStart) values (971, 'Funes', 1997);
insert into Branch (id, location, yearStart) values (972, 'Sentul', 2008);
insert into Branch (id, location, yearStart) values (973, 'Kotabumi', 1965);
insert into Branch (id, location, yearStart) values (974, 'Krajan Atas Suger Lor', 1996);
insert into Branch (id, location, yearStart) values (975, 'Banjar Sengguan', 2005);
insert into Branch (id, location, yearStart) values (976, 'Marale', 2011);
insert into Branch (id, location, yearStart) values (977, 'Longcheng', 2009);
insert into Branch (id, location, yearStart) values (978, 'Raoyang', 1997);
insert into Branch (id, location, yearStart) values (979, 'Xiumei', 1993);
insert into Branch (id, location, yearStart) values (980, 'Muruni', 2003);
insert into Branch (id, location, yearStart) values (981, 'Czarna', 1987);
insert into Branch (id, location, yearStart) values (982, 'Corpus Christi', 2009);
insert into Branch (id, location, yearStart) values (983, 'Kushk', 2005);
insert into Branch (id, location, yearStart) values (984, 'Ulundi', 1993);
insert into Branch (id, location, yearStart) values (985, 'Göteborg', 2010);
insert into Branch (id, location, yearStart) values (986, 'Kuching', 2002);
insert into Branch (id, location, yearStart) values (987, 'Ayabaca', 1997);
insert into Branch (id, location, yearStart) values (988, 'Xidianzi', 1965);
insert into Branch (id, location, yearStart) values (989, 'Kāshmar', 1992);
insert into Branch (id, location, yearStart) values (990, 'Shiyu', 1995);
insert into Branch (id, location, yearStart) values (991, 'Cibolek Kidul', 2012);
insert into Branch (id, location, yearStart) values (992, 'Xinhui', 1993);
insert into Branch (id, location, yearStart) values (993, 'Tianzishan', 2007);
insert into Branch (id, location, yearStart) values (994, 'Orange Walk', 1984);
insert into Branch (id, location, yearStart) values (995, 'Oenaik', 2012);
insert into Branch (id, location, yearStart) values (996, 'Na Kae', 2002);
insert into Branch (id, location, yearStart) values (997, 'Gadang', 1989);
insert into Branch (id, location, yearStart) values (998, 'Khadan Khāk', 2006);
insert into Branch (id, location, yearStart) values (999, 'Hukeng', 2000);
insert into Branch (id, location, yearStart) values (1000, 'Pryluky', 2006);
